services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: discordbot
    restart: unless-stopped
    env_file: ./botdata/.env
    #volumes:
    #- ./botdata:/home/node/app
    #- ./botdata/node_modules:/home/node/app/node_modules
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"


volumes:
  botdata:
  node_modules:

networks:
  app-network:
